### ISSUE TITLE
What is the format of the input file?

### ISSUE THREAD

**Issue by kuangzhuoran** [marqueda/HMM-detection-of-genomic-islands#1]
I cannot understand "filename.suffix is a file with FST values with a header 'x'"

**Comment by marqueda** [comment]
filename.suffix stands as a placeholder for the name of your input file, e.g. myfstvalues.txt with "myfstvalues" being the filename and "txt" being the suffix separated by a period ".". It is written like that because the script writes output files that re-use the filename as prefix, e.g. "myfstvalues_inputdata_histogram.pdf" etc.

Then the "FST values with a header 'x'" means that the file contains FST values, one per row, and that the top row contains the entry 'x'. I have to admit that is a bit stupid and arose just from saving vectors in R and then re-loading them again, so historic reasons.

I hope this helps!
